#!/bin/python

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1,2,3,5,8,13,21,34,55,89,...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

LIMIT = 4000000

a = 1
b = 2
even = [2]

while True:
  next = a + b
  if next > LIMIT:
    break
  else:
    a = b
    b = next
    if next % 2 == 0:
      even.append(next)

print(sum(even))  
